### ISSUE TITLE
Feature request: OS detection with handshake

### ISSUE THREAD

**Issue by LinuxHeki** [rust-embedded-community/usb-device#106]
Is it possible to implement OS detection with handshake?

**Comment by ryan-summers** [comment]
I'm not sure this would belong in usb-device given that USB has no concept of an OS. There are only USB hsots and devices. A USB host may very well be an embedded device or custom hardware.

While OSes do have subtle differences in how they do enumeration, I'm not sure this is something that should ever be relied on, as it would be subject to change without notice.

**Comment by Disasm** [comment]
@stappersg putting aside the opinion that such comments are not appropriate, I'd remind that the question of the ticket is not about "why", it's about "how". There is a demand for OS detection, so it's ok to express curiosity about implementation.

USB enumeration process indeed looks differently depending on OS, and these differences can be used to create _heuristics_ for OS detection. Is it possible to do this with this library? Well, probably not out of the box, one will have to augment USB driver for their MCU to gather more information about enumeration sequence.

**Comment by ryan-summers** [comment]
> USB enumeration process indeed looks differently depending on OS, and these differences can be used to create heuristics for OS detection. Is it possible to do this with this library? Well, probably not out of the box, one will have to augment USB driver for their MCU to gather more information about enumeration sequence.

Yes, I could have been more clear in my answer, but e.g. Ubuntu and Windows _do_ have differences in how they perform enumeration processes (see https://github.com/rust-embedded-community/usb-device/issues/82 for a direct example of this), so you can _theoretically_ create a method to detect that difference. However, @Disasm makes a great point here in that this is a _heuristic_. It can't be relied upon for anything important and would be subject to change without notice as the OS vendor may modify their USB enumeration sequencing.

Additionally, there may even be differences between different patches of the same OS vendor (e.g. differences between Windows 20H2 and Windows 21H1).

Doing some detection mechanism is definitely possible. However, I am against implementing such a detection mechanism into `usb-device` directly.

**Comment by ryan-summers** [comment]
Given that there are no plans to implement this into `usb-device` currently (and I don't foresee this as feasible either), I'm going to close this issue. Thanks for bringing up the idea though!
