### ISSUE TITLE
Replace usage of `expect()` with returning `Result<>` types

### ISSUE THREAD

**Issue by ryan-summers** [rust-embedded-community/usb-device#113]
Currently, there's a number of places where `expect()` is called on `Result<>` types. This can introduce format bloat into end-user applications, which may be undesirable.

Instead, we should propagate the `Result<>` out to the user to allow them to decide what to do with the error.

**Comment by AlexanderDefuria** [comment]
Has someone started on this?

**Comment by eldruin** [comment]
Not that I know of. Please feel free to give it a try.

**Comment by AlexanderDefuria** [comment]
I'll take a stab at this. Thanks!
