### ISSUE TITLE
How do I implement a device with multiple classes

### ISSUE THREAD

**Issue by arkap** [rust-embedded-community/usb-device#85]
I'm struggling to understand how one would create a UsbDevice which announces itself as two devices. In my case I would like it to both be a serial port and a MIDI device. From the descriptions it seems I would have to create only one UsbDevice but How can I tell that device that it has multiple classes?

**Comment by Disasm** [comment]
Yes, you need to create one `UsbDevice` and multiple classes. Then you pass all the classes as an argument to `UsbDevice::poll()`.

**Comment by arkap** [comment]
Thank you. I keep running into problems. This is what I've done:

1. create a USB serial class (`usbd_serial::SerialPort`)
2. create a USB MIDI class (`usbd_midi::midi_device::MidiClass`)
3. create a `UsbDevice`

My issues are as follows: If I create the `UsbDevice` before the `UsbClass`es it does not get recognized
```
usb 1-1: device descriptor read/64, error -110
```

If I create the `UsbDevice` after the `UsbClass`es and poll like this `dev.poll(&mut [serial, midi])`, I get
```
usb 1-1: new full-speed USB device number 97 using xhci_hcd
usb 1-1: unable to read config index 0 descriptor/start: -32
usb 1-1: chopping to 0 config(s)
usb 1-1: can't read configurations, error -32
```

If I create the `UsbDevice` after the `UsbClass`es and poll like this `dev.poll(&mut [midi])`, i.e. only the `MidiClass`, I get
```
usb 1-1: new full-speed USB device number 110 using xhci_hcd
usb 1-1: config 1 has an invalid interface number: 2 but max is 1
usb 1-1: config 1 has an invalid interface number: 3 but max is 1
usb 1-1: config 1 has no interface number 0
usb 1-1: config 1 has no interface number 1
usb 1-1: New USB device found, idVendor=2222, idProduct=3333, bcdDevice= 0.10
usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
usb 1-1: Product: XXX
usb 1-1: Manufacturer: XXX
usb 1-1: SerialNumber: XXX
usb 1-1: 2:1 : does not exist

If I create the `UsbDevice` after the `UsbClass`es and poll only `serial`, I get a working USB serial connection.

It looks to me like there is something wrong with how the `MidiClass` handles the handshake with the USB host. Any ideas on how to narrow down the error here?

**Comment by Disasm** [comment]
Try `control-buffer-256` feature of `usb-device`, probably 128-byte buffer is too small for both serial and MIDI.
And yes, you need to create `UsbDevice` after `UsbClass`es and then pass all the classes to `dev.poll`.

**Comment by arkap** [comment]
Yes, that fixed it. Thank you! :)

**Comment by ryan-summers** [comment]
It seems to me that with const-generics, or with `managed`, we can make the control buffer allocation simpler. I've opened https://github.com/rust-embedded-community/usb-device/issues/90 to track this, but it sounds like otherwise your issue has been resolved, so I'm closing this issue.
