### ISSUE TITLE
Why does Suspend always transition to Default on Resume?

### ISSUE THREAD

**Issue by haata** [rust-embedded-community/usb-device#96]
I noticed an oddity testing remote wakeup where if another device does the wakeup and the device under test resumes usb-device crate will set the state to UsbDeviceState::Default rather than the previous state.

My general understanding of the state transitions follows (https://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-11100-32-bit%20Cortex-M4-Microcontroller-SAM4S_Datasheet.pdf; 40.6.3 page 1042).
![screenshot7](https://user-images.githubusercontent.com/23465/173131660-e497342b-5dbf-40f5-962f-3de4053314da.png)

This diagram implies that when transitioning back from Suspend, you should go back to the previous state, rather than Default state.

https://github.com/rust-embedded-community/usb-device/blob/413b77cd38d200c3b0e777dd3055cb7ef82c46a0/src/device.rs#L162-L175

Is this intended? Should I make a PR to fix it?

**Comment by mvirkkunen** [comment]
Yes, this is currently implemented wrong. Somebody mentioned this on the Matrix channel before and I found the same picture, and I think I misread the specification when I originally wrote that logic. I guess nobody thought to open an issue about it back then, so good that you did now.
